CREATE TABLE IF NOT EXISTS logistics_products (
  id TEXT PRIMARY KEY,
  product_code TEXT NOT NULL UNIQUE,
  product_name TEXT NOT NULL,
  channel_product_id TEXT,
  channel_product_code TEXT,
  channel_product_name TEXT,
  route_name TEXT,
  origin_country_code TEXT NOT NULL,
  origin_country_name TEXT NOT NULL,
  origin_city TEXT,
  destination_country_code TEXT NOT NULL,
  destination_country_name TEXT NOT NULL,
  destination_city TEXT,
  estimated_days TEXT,
  support_categories TEXT NOT NULL DEFAULT '[]',
  forbidden_categories TEXT NOT NULL DEFAULT '[]',
  charge_weight_mode TEXT NOT NULL DEFAULT 'max_actual_volume',
  pricing_mode TEXT NOT NULL DEFAULT 'first_additional',
  min_weight REAL NOT NULL DEFAULT 0.5,
  max_weight REAL NOT NULL DEFAULT 30,
  volume_divisor REAL NOT NULL DEFAULT 5000,
  rounding_unit REAL NOT NULL DEFAULT 0.5,
  density_threshold REAL NOT NULL DEFAULT 120,
  density_low_mode TEXT NOT NULL DEFAULT 'volume',
  density_high_mode TEXT NOT NULL DEFAULT 'actual',
  first_weight REAL NOT NULL DEFAULT 1,
  first_price REAL NOT NULL DEFAULT 0,
  additional_weight REAL NOT NULL DEFAULT 0.5,
  additional_price REAL NOT NULL DEFAULT 0,
  price_tiers TEXT,
  attribute_surcharges TEXT,
  handling_fee REAL NOT NULL DEFAULT 0,
  fuel_surcharge_rate REAL NOT NULL DEFAULT 0,
  cargo_surcharge_rate REAL NOT NULL DEFAULT 0,
  is_tax_included INTEGER NOT NULL DEFAULT 0,
  need_identity INTEGER NOT NULL DEFAULT 0,
  support_tracking INTEGER NOT NULL DEFAULT 1,
  status TEXT NOT NULL DEFAULT 'active',
  remarks TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (channel_product_id) REFERENCES channel_products(id)
);

CREATE INDEX IF NOT EXISTS idx_logistics_products_status ON logistics_products (status);
CREATE INDEX IF NOT EXISTS idx_logistics_products_route ON logistics_products (origin_country_code, destination_country_code);
CREATE INDEX IF NOT EXISTS idx_logistics_products_channel_product ON logistics_products (channel_product_id);
